#!/usr/bin/env bash
set -euo pipefail

GO_VERSION="${GO_VERSION:-1.25.4}"
GOLANGCI_LINT_VERSION="${GOLANGCI_LINT_VERSION:-v2.6.1}"
GOFUMPT_VERSION="${GOFUMPT_VERSION:-v0.9.2}"
ACTIONLINT_VERSION="${ACTIONLINT_VERSION:-v1.7.8}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="${HOME}/.config/oci-cpu-shaper"
ENV_FILE="${ENV_DIR}/env.sh"

log() {
    printf '[setup-codex-env] %s\n' "$*"
}

ensure_packages() {
    local sudo_prefix=""
    if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
        sudo_prefix="sudo"
    fi
    export DEBIAN_FRONTEND=noninteractive
    ${sudo_prefix} apt-get update -y
    ${sudo_prefix} apt-get install -y --no-install-recommends \
        bash-completion ca-certificates curl git make tar build-essential
}

install_go() {
    local arch download_arch tarball tmpdir sudo_prefix=""
    if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
        sudo_prefix="sudo"
    fi
    arch="$(dpkg --print-architecture)"
    case "${arch}" in
        amd64|x86_64) download_arch="amd64" ;;
        arm64|aarch64) download_arch="arm64" ;;
        *)
            log "Unsupported architecture: ${arch}"
            exit 1
            ;;
    esac

    if command -v go >/dev/null 2>&1 && go version | grep -q "go${GO_VERSION} " ; then
        log "Go ${GO_VERSION} already installed"
        return
    fi

    tarball="go${GO_VERSION}.linux-${download_arch}.tar.gz"
    tmpdir="$(mktemp -d)"
    log "Downloading Go ${GO_VERSION} (${download_arch})"
    curl -fsSL "https://go.dev/dl/${tarball}" -o "${tmpdir}/${tarball}"
    log "Installing Go to /usr/local"
    ${sudo_prefix} rm -rf /usr/local/go
    ${sudo_prefix} tar -C /usr/local -xzf "${tmpdir}/${tarball}"
    rm -rf "${tmpdir}"
}

write_env_file() {
    mkdir -p "${ENV_DIR}" "${REPO_ROOT}/.cache"
    cat > "${ENV_FILE}" <<EOF_ENV
# Generated by hack/setup-codex-env.sh. Source from your shell profile.
export GOPATH="\${HOME}/go"
export GOBIN="\${HOME}/go/bin"
export PATH="/usr/local/go/bin:\${HOME}/go/bin:\$PATH"
export GOCACHE="${REPO_ROOT}/.cache/go"
export GOLANGCI_LINT_CACHE="${REPO_ROOT}/.cache/golangci"
export GOMODCACHE="${REPO_ROOT}/.cache/gomod"
export GOTOOLCHAIN="local"
EOF_ENV

    if ! grep -Fq "${ENV_FILE}" "${HOME}/.bashrc" 2>/dev/null; then
        {
            echo ""
            echo "# OCI CPU Shaper Go environment"
            echo "if [ -f \"${ENV_FILE}\" ]; then"
            echo "    . \"${ENV_FILE}\""
            echo "fi"
        } >> "${HOME}/.bashrc"
    fi

    # shellcheck disable=SC1090
    . "${ENV_FILE}"
}

install_tools() {
    mkdir -p "${GOBIN}" "${GOCACHE}" "${GOLANGCI_LINT_CACHE}" "${GOMODCACHE}"
    log "Installing Go tooling (golangci-lint ${GOLANGCI_LINT_VERSION}, gofumpt ${GOFUMPT_VERSION})"
    go install "github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}"
    go install "mvdan.cc/gofumpt@v${GOFUMPT_VERSION}"
    go install "github.com/rhysd/actionlint/cmd/actionlint@${ACTIONLINT_VERSION}"
}

sync_repo_assets() {
    log "Downloading module dependencies into ${GOMODCACHE}"
    GOMODCACHE="${GOMODCACHE}" GOCACHE="${GOCACHE}" go mod download
    log "Ensuring Makefile-managed tools are current"
    make -C "${REPO_ROOT}" tools
}

enable_git_hooks() {
    if git -C "${REPO_ROOT}" rev-parse --git-dir >/dev/null 2>&1; then
        log "Enabling repository git hooks"
        git -C "${REPO_ROOT}" config core.hooksPath .githooks
        find "${REPO_ROOT}/.githooks" -maxdepth 1 -type f -exec chmod +x {} +
    fi
}

main() {
    log "Bootstrapping Go ${GO_VERSION} toolchain"
    ensure_packages
    install_go
    write_env_file
    install_tools
    sync_repo_assets
    enable_git_hooks
    log "Environment ready. Reload your shell or source ${ENV_FILE} to pick up PATH/GOPATH updates."
}

main "$@"
